name: Node.js CI
run-name: PR ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

env:
  CI: true
  env: test

jobs:
  test:
    name: "🧪 Tests"
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run demo
        run: npm run demo

      - name: Run demo-stop-all
        run: npm run demo-stop-all
